# Generated by Django 3.2.4 on 2021-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Producto')),
                ('imagen', models.ImageField(default='null', upload_to='', verbose_name='Imagen del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Producto')),
                ('artista', models.CharField(max_length=20, verbose_name='Artista de Producto')),
                ('estado', models.BooleanField(default='null', verbose_name='Estado del Producto')),
                ('fechaCrea', models.CharField(max_length=10, verbose_name='Fecha de Creacion')),
            ],
        ),
    ]
