# Generated by Django 3.2.4 on 2021-06-28 18:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden de las paginas'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion del Pagina'),
        ),
    ]
