# Generated by Django 3.2.4 on 2021-06-28 18:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaArt',
            fields=[
                ('idCategoria', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idProducto', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('imagen', models.ImageField(default='null', upload_to='productos', verbose_name='Imagen del Producto')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion del Producto')),
                ('artista', models.CharField(max_length=20, verbose_name='Artista de Producto')),
                ('estado', models.BooleanField(verbose_name='Estado del Producto')),
                ('fechaCrea', models.CharField(max_length=10, verbose_name='Fecha de Creacion')),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='blog.CategoriaArt', verbose_name='Categorias del articulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
