# Generated by Django 3.2.4 on 2021-06-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='user',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='artista',
            field=models.CharField(max_length=30, verbose_name='Nombre del Artista'),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='categorias',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categoriaart', verbose_name='Categorias del articulo'),
            preserve_default=False,
        ),
    ]
