# Generated by Django 3.2.4 on 2021-06-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210628_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fechaCrea',
            field=models.DateField(max_length=10, verbose_name='Fecha de Creacion'),
        ),
    ]
