# Generated by Django 3.2.4 on 2021-06-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articulo_fechacrea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fechaCrea',
            new_name='fecha_crea',
        ),
    ]
