# Generated by Django 3.2.4 on 2021-07-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_fechacrea_articulo_fecha_crea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.BooleanField(null=True, verbose_name='Estado del Producto'),
        ),
    ]
